### ISSUE TITLE
RAT-5 Update Readme.md file

### ISSUE THREAD

**Issue by fookoo** [rrasta/rasta-todo#6]
Provide information about app.

**Comment by rrasta** [comment]
What information do you expect?
Present state   or the final appearance of the app.

**Comment by rrasta** [comment]
I update redme.me. But Im not sure it is ok?

**Comment by fookoo** [comment]
Is not

What is wrong:
- you create branch with wrong name, it should be 'feature/RAT-5-update-reade-me',
So the key here is to use 'feature/' prefix and also task reference (uppercase), then name of branch, (lowercase)

- You add some additional text (99% unintended)
- You create pull request, from your branch to another branch, instead to master
- Readme, should contain:
  - Project name & short descriptions, bonus is a screenshot 
  - Quick help how to quickly: clone, build, run project
```
git clone https://github.com/rrasta/rasta-todo
cd rasta-todo
npm/yarn install
npm/yarn start
```
- Authors

Readme.md
